# More about Customizing static analysis:
# https://dart.dev/guides/language/analysis-options#ignoring-rules

include: package:pedantic/analysis_options.yaml

# analyzer:
#   exclude:
#     - lib/client.dart
#     - lib/server/*.g.dart
#     - test/_data/**
#   strong-mode:
#     implicit-casts: false
#     implicit-dynamic: false
#   errors:
#     omit_local_variable_types: ignore

linter:
  rules:
    - prefer_int_literals
    - avoid_print
    # - always_specify_types
